/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorChofer;
import controlador.ControladorDespacho;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import modelo.Despacho;

/**
 *
 * @author user
 */
public class InformacionDespacho extends javax.swing.JFrame {

    /**
     * Creates new form InformacionDespacho
     */
    public InformacionDespacho() {
        initComponents();
    }
    
    public InformacionDespacho(ArrayList<String> datos){
        initComponents();
        ControladorChofer conChofer = new ControladorChofer();
        
        ArrayList<String> listaChoferes = conChofer.listarChofer(this);
        for(String chofer: listaChoferes){
            cbb_chofer.addItem(chofer);
        }
        
        
        lbl_hora.setText(datos.get(0));
        cbb_chofer.setSelectedItem(datos.get(1));
        cbb_vehiculo.setSelectedItem(datos.get(2));
        lbl_vendedor.setText(datos.get(3));
        txt_Destino.setText(datos.get(4));
        lbl_idDespacho.setText(datos.get(5));
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lbl_hora = new javax.swing.JLabel();
        lbl_vendedor = new javax.swing.JLabel();
        lbl_idDespacho = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Destino = new javax.swing.JTextArea();
        lbl_idDespacho1 = new javax.swing.JLabel();
        lbl_idDespacho2 = new javax.swing.JLabel();
        lbl_idDespacho3 = new javax.swing.JLabel();
        lbl_idDespacho4 = new javax.swing.JLabel();
        lbl_idDespacho5 = new javax.swing.JLabel();
        cbb_vehiculo = new javax.swing.JComboBox<>();
        cbb_chofer = new javax.swing.JComboBox<>();
        btn_actualizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transportes Garetto | Informacion despacho");
        setResizable(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informacion despacho seleccionado", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14), new java.awt.Color(51, 102, 0))); // NOI18N

        lbl_hora.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_hora.setForeground(new java.awt.Color(0, 0, 204));

        lbl_vendedor.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_vendedor.setForeground(new java.awt.Color(0, 0, 204));

        lbl_idDespacho.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_idDespacho.setForeground(new java.awt.Color(0, 0, 204));

        txt_Destino.setColumns(20);
        txt_Destino.setRows(5);
        jScrollPane2.setViewportView(txt_Destino);

        lbl_idDespacho1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_idDespacho1.setForeground(new java.awt.Color(0, 0, 102));
        lbl_idDespacho1.setText("COD. DESPACHO");

        lbl_idDespacho2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_idDespacho2.setForeground(new java.awt.Color(0, 0, 102));
        lbl_idDespacho2.setText("HORA SALIDA");

        lbl_idDespacho3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_idDespacho3.setForeground(new java.awt.Color(0, 0, 102));
        lbl_idDespacho3.setText("CHOFER");

        lbl_idDespacho4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_idDespacho4.setForeground(new java.awt.Color(0, 0, 102));
        lbl_idDespacho4.setText("VEHICULO");

        lbl_idDespacho5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_idDespacho5.setForeground(new java.awt.Color(0, 0, 102));
        lbl_idDespacho5.setText("VENDEDOR");

        cbb_vehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "FIORINO", "STRADA", "GAC", "HILUX", "CAMION", "DFSK TRUCK" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_idDespacho1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_idDespacho2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_idDespacho3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_idDespacho5, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_idDespacho, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(lbl_vendedor, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(lbl_hora, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(cbb_chofer, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbl_idDespacho4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cbb_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_idDespacho, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_idDespacho1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_idDespacho2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_idDespacho3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_chofer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_idDespacho4, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbb_vehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbl_idDespacho5, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_actualizar.setText("Actualizar informacion");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addComponent(btn_actualizar)
                .addGap(20, 20, 20))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(405, Short.MAX_VALUE)
                .addComponent(btn_actualizar)
                .addGap(19, 19, 19))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(54, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        ControladorDespacho conDespacho = new ControladorDespacho();
        conDespacho.actualizarDestinoVehiculo(this, lbl_idDespacho.getText(), txt_Destino.getText(), (String) cbb_vehiculo.getSelectedItem(), cbb_chofer.getSelectedIndex()+1);
       
    }//GEN-LAST:event_btn_actualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InformacionDespacho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InformacionDespacho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InformacionDespacho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InformacionDespacho.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InformacionDespacho().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JComboBox<String> cbb_chofer;
    private javax.swing.JComboBox<String> cbb_vehiculo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbl_hora;
    private javax.swing.JLabel lbl_idDespacho;
    private javax.swing.JLabel lbl_idDespacho1;
    private javax.swing.JLabel lbl_idDespacho2;
    private javax.swing.JLabel lbl_idDespacho3;
    private javax.swing.JLabel lbl_idDespacho4;
    private javax.swing.JLabel lbl_idDespacho5;
    private javax.swing.JLabel lbl_vendedor;
    private javax.swing.JTextArea txt_Destino;
    // End of variables declaration//GEN-END:variables
}
