/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author user
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem6 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_ingresoKilometraje = new javax.swing.JMenuItem();
        mi_solicitudTransporte = new javax.swing.JMenuItem();
        mi_despachoFecha = new javax.swing.JMenuItem();
        mi_documentacionEntregada = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mi_listadoKilometraje = new javax.swing.JMenuItem();
        mi_revisionTecnica = new javax.swing.JMenuItem();
        mi_revisionGases = new javax.swing.JMenuItem();
        mi_reparacion = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mi_informacionVehiculos = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        mi_ingresarVendedor = new javax.swing.JMenuItem();
        mi_quitarVendedor = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        mi_ingresarChofer = new javax.swing.JMenuItem();
        mi_quitarChofer = new javax.swing.JMenuItem();

        jMenuItem6.setText("jMenuItem6");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transportes Garetto");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondoTransportes.jpg"))); // NOI18N

        jMenu1.setText("DIARIO");

        mi_ingresoKilometraje.setText("INGRESO KILOMETRAJE");
        mi_ingresoKilometraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_ingresoKilometrajeActionPerformed(evt);
            }
        });
        jMenu1.add(mi_ingresoKilometraje);

        mi_solicitudTransporte.setText("SOLICITUD DE TRANSPORTE");
        mi_solicitudTransporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_solicitudTransporteActionPerformed(evt);
            }
        });
        jMenu1.add(mi_solicitudTransporte);

        mi_despachoFecha.setText("DESPACHOS POR FECHA");
        mi_despachoFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_despachoFechaActionPerformed(evt);
            }
        });
        jMenu1.add(mi_despachoFecha);

        mi_documentacionEntregada.setText("DOCUMENTACION ENTREGADA");
        mi_documentacionEntregada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_documentacionEntregadaActionPerformed(evt);
            }
        });
        jMenu1.add(mi_documentacionEntregada);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("REVISIONES");

        mi_listadoKilometraje.setText("LISTADO KILOMETRAJE");
        mi_listadoKilometraje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_listadoKilometrajeActionPerformed(evt);
            }
        });
        jMenu2.add(mi_listadoKilometraje);

        mi_revisionTecnica.setText("REVISION TECNICA");
        jMenu2.add(mi_revisionTecnica);

        mi_revisionGases.setText("REVISION DE GASES");
        jMenu2.add(mi_revisionGases);

        mi_reparacion.setText("REPARACION");
        jMenu2.add(mi_reparacion);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("VEHICULOS");

        mi_informacionVehiculos.setText("INFORMACION VEHICULOS");
        jMenu3.add(mi_informacionVehiculos);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("PERSONAL");

        jMenu5.setText("VENDEDOR");

        mi_ingresarVendedor.setText("INGRESAR VENDEDOR");
        mi_ingresarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_ingresarVendedorActionPerformed(evt);
            }
        });
        jMenu5.add(mi_ingresarVendedor);

        mi_quitarVendedor.setText("QUITAR VENDEDOR");
        jMenu5.add(mi_quitarVendedor);

        jMenu4.add(jMenu5);

        jMenu6.setText("CHOFER");

        mi_ingresarChofer.setText("INGRESAR CHOFER");
        mi_ingresarChofer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_ingresarChoferActionPerformed(evt);
            }
        });
        jMenu6.add(mi_ingresarChofer);

        mi_quitarChofer.setText("QUITAR CHOFER");
        jMenu6.add(mi_quitarChofer);

        jMenu4.add(jMenu6);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mi_ingresoKilometrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_ingresoKilometrajeActionPerformed
        IngresoKilometraje ventana = new IngresoKilometraje();
        ventana.setVisible(true);
    }//GEN-LAST:event_mi_ingresoKilometrajeActionPerformed

    private void mi_solicitudTransporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_solicitudTransporteActionPerformed
        SolicitudTransporte ventana = new SolicitudTransporte();
        ventana.setVisible(true);
    }//GEN-LAST:event_mi_solicitudTransporteActionPerformed

    private void mi_ingresarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_ingresarVendedorActionPerformed
        IngresarVendedor ventana = new IngresarVendedor();
        ventana.setVisible(true);
    }//GEN-LAST:event_mi_ingresarVendedorActionPerformed

    private void mi_ingresarChoferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_ingresarChoferActionPerformed
        IngresarChofer ventana = new IngresarChofer();
        ventana.setVisible(true);
    }//GEN-LAST:event_mi_ingresarChoferActionPerformed

    private void mi_despachoFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_despachoFechaActionPerformed
        DespachoPorFecha ventana = new DespachoPorFecha();
        ventana.setVisible(true);
    }//GEN-LAST:event_mi_despachoFechaActionPerformed

    private void mi_documentacionEntregadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_documentacionEntregadaActionPerformed
        DocEntregado ventana = new DocEntregado();
        ventana.setVisible(true);
    }//GEN-LAST:event_mi_documentacionEntregadaActionPerformed

    private void mi_listadoKilometrajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_listadoKilometrajeActionPerformed
        ListadoKilometraje ventana = new ListadoKilometraje();
        ventana.setVisible(true);
    }//GEN-LAST:event_mi_listadoKilometrajeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem mi_despachoFecha;
    private javax.swing.JMenuItem mi_documentacionEntregada;
    private javax.swing.JMenuItem mi_informacionVehiculos;
    private javax.swing.JMenuItem mi_ingresarChofer;
    private javax.swing.JMenuItem mi_ingresarVendedor;
    private javax.swing.JMenuItem mi_ingresoKilometraje;
    private javax.swing.JMenuItem mi_listadoKilometraje;
    private javax.swing.JMenuItem mi_quitarChofer;
    private javax.swing.JMenuItem mi_quitarVendedor;
    private javax.swing.JMenuItem mi_reparacion;
    private javax.swing.JMenuItem mi_revisionGases;
    private javax.swing.JMenuItem mi_revisionTecnica;
    private javax.swing.JMenuItem mi_solicitudTransporte;
    // End of variables declaration//GEN-END:variables
}
